import "./style.scss"
import "./scripts/localstorage"
import "./scripts/darkmode"
import "./scripts/touch"
import "./images/Arrow_Left.png"
import "./images/Setting_icon.png"
import "./scripts/fetch.js"