import "./style.scss"
//import "./scripts/localstorage"
//import "./scripts/darkmode"
//import "./scripts/touch"
import "./scripts/fetch"
//import "./images/Arrow_Left.png"
//import "./images/Setting_icon.png"