import "./style.scss"
import "./scripts/getJSONfromLocalStorage"
import "./scripts/deleteJSONfromLocalStorage"
import "./scripts/inbox"
//import "./images/Arrow_Left.png"
//import "./images/Setting_icon.png"